apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: os
            operator: In
            values:
            - linux          
  containers:
  - name: nginx2
    image: nginx
    imagePullPolicy: IfNotPresent

